sudo: required
services: 
  - docker

before_install:
  - docker build -t therealsheng/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run therealsheng/react-test npm test -- --coverage

after_success:
  - docker build -t therealsheng/multi-client ./client
  - docker build -t therealsheng/multi-nginx ./nginx
  - docker build -t therealsheng/multi-server ./server
  - docker build -t therealsheng/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take this images and Push them into docker hub
  - docker push therealsheng/multi-client
  - docker push therealsheng/multi-nginx
  - docker push therealsheng/multi-server
  - docker push therealsheng/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: muilti-docker
  env: MuiltiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-548876645614
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
      secure: "$AWS_SECRET_KEY"
